### ISSUE TITLE
`filter_by_sf()` function

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfstools#24]
A function to _"Develop a function to reduce a GTFS feed to within a defined bounding box, through removing all routes which do not pass within the bounding box at all."_, as mentioned by @mpadge [here](https://github.com/ATFutures/gtfs-router/issues/44).

I remember @dhersz had something similar to this, but it would be nice to hear from @mpadge what he has in mind.

**Comment by dhersz** [comment]
Yup, there is this issue open as well: https://github.com/ipeaGIT/gtfstools/issues/17 (though I'd suggest calling it `crop_gtfs()` instead of `crop_by_sf()` :P).

The idea is pretty much what @mpadge has stated already. But I initially though of it receiving a `sf` or even a plain `sfc` (a geometry column). If by bounding box Mark means literally a bouding box rectangle, it could also receive a numeric vector of length 4, each entry representing an edge of the box, from which we could build a polygon to intersect the shapes and stops with.

**Comment by rafapereirabr** [comment]
I agree `crop_gtfs()`is a much better name for the function than `crop_by_sf()`

**Comment by mpadge** [comment]
And just for clarity: I intend(ed) throughout to imply "bounding polygon", and not just "bounding box". And since `sf` is already imported here, there shouldn't be any issue with expecting an `sf` format input, including `st_bbox()`. Numeric vector input is really difficult to get right - I've given it a go in `osmdata`, but even then it's fragile and something that i would not recommend.

**Comment by dhersz** [comment]
A first version was added in https://github.com/ipeaGIT/gtfstools/commit/0606149125295669ad04d887f46a7be95c5f62b4. I decided to name it `filter_by_sf()` because using crop would "nudge it" towards a specific spatial operation. With the current implementation you can specify which spatial operation you want to use to filter - e.g. [intersection, contain, cross, etc.](https://r-spatial.github.io/sf/reference/geos_binary_pred.html)

https://github.com/ipeaGIT/gtfstools/blob/0606149125295669ad04d887f46a7be95c5f62b4/R/filter_by_sf.R#L51-L54

I still got to:
- [ ] Support other classes in `geom` (right now only supports sf objects, I plan to accept sfc and bbox objects as well);
- [ ] Add tests.

**Comment by dhersz** [comment]
Finally done :)

Here is some code snippet that visually show how it works.

``` r
library(gtfstools)
library(ggplot2)

plotter <- function(gtfs,
                    geom,
                    spatial_operation = sf::st_intersects,
                    keep = TRUE,
                    do_filter = TRUE) {

  if (do_filter)
    gtfs <- filter_by_sf(gtfs, geom, spatial_operation, keep)

  shapes <- convert_shapes_to_sf(gtfs)
  trips <- get_trip_geometry(gtfs, file = "stop_times")
  geom <- gtfstools:::polygon_from_bbox(geom)

  ggplot() +
    geom_sf(data = trips) +
    geom_sf(data = shapes) +
    geom_sf(data = geom, fill = NA)

}

path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")
gtfs <- read_gtfs(path)

bbox <- sf::st_bbox(convert_shapes_to_sf(gtfs, shape_id = "68962"))

# unfiltered
plotter(gtfs, bbox, do_filter = FALSE)
```

![](https://i.imgur.com/NYSRzF5.png)

``` r

# keeping intersected
plotter(gtfs, bbox)
```

![](https://i.imgur.com/VlgUh0Z.png)

``` r

# dropping intersected
plotter(gtfs, bbox, keep = FALSE)
```

![](https://i.imgur.com/Ek4fAgP.png)

``` r

# keeping contained
plotter(gtfs, bbox, spatial_operation = sf::st_contains)
```

![](https://i.imgur.com/HNquCHG.png)

``` r

# dropping contained
plotter(gtfs, bbox, spatial_operation = sf::st_contains, keep = FALSE)
```

![](https://i.imgur.com/QDOYsVg.png)

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
