### ISSUE TITLE
Issue getting GTFS data into R to filter

### ISSUE THREAD

**Issue by LeonLeprau** [ipeaGIT/gtfstools#49]
Hi there,

So this is the first time i've used R to deal with GTFS data and I've run into an issue pretty early on.
after figuring out all the necessary packages and tools needed I'm trying to read my GTFS zip data file as per the 'GTFS filter instructions'

So I try to set up the path and then get R to read the data

> data_path <- system.file("C:/Users/leond/OneDrive/Documents/itm_north_east_gtfs.zip", package = "gtfstools")
> gtfs <- read_gtfs(data_path)

to which I'm faced with the error 
> Error 'path' must have '.zip' extension.

when I google this error I get no clear answers, from what I can understand anyway.

I've made sure that my GTFS file is in zip form (which is how it comes on download), and then I copied the location of the file and wrote out the command as it says to in the instructions for 'GTFS Filter'.

any help with this would be appreciated. Thanks so much.

All the best,
Leon

**Comment by dhersz** [comment]
Hi @LeonLeprau. You're mistakenly using `system.file()`. This function is used to access files that are installed with the package, such as the ones I use in the examples and vignettes, but not to access files distributed in your file system.

Unfortunately the function doesn't raise a warning/error when used inappropriately, but you can see what happens below:

``` r
system.file("extdata/spo_gtfs.zip", package = "gtfstools")
#> [1] "/home/dhersz/R/x86_64-pc-linux-gnu-library/4.1/gtfstools/extdata/spo_gtfs.zip"

system.file("non_existent_file.zip", package = "gtfstools")
#> [1] ""
```

It simply returns an empty string, and that's why `read_gtfs()` complains about the file extension.

The solution in you case is just to use the path you wrapped into `system.file()` directly:

```r
gtfs <- read_gtfs("C:/Users/leond/OneDrive/Documents/itm_north_east_gtfs.zip")
```

**Comment by LeonLeprau** [comment]
Ah that makes sense. thanks so much for your help and replying so promptly.

Have a good day :)
