### ISSUE TITLE
help with Stop_id Filter

### ISSUE THREAD

**Issue by LeonLeprau** [ipeaGIT/gtfstools#50]
Hi again,

So I've used excel to put my stop_id data into the correct format e.g. ("18848", "940004157") and then set up the command 
 > stop_ids <-  C("x", "x" and so on) to continue with the filter process. 

When I try to run it presents me with an (+) implying that more code needs to be written. I'm sure that its all in the same format as the example. I have 4031 individual stop_id's so I've just attached screenshots of the start and the end.

Thanks so much for your help with this its really appreciated.

![Capture](https://user-images.githubusercontent.com/101003351/161268406-cc1f6f88-b5ef-4188-b9c0-d8e6cb821a1d.PNG)
![Capture 2](https://user-images.githubusercontent.com/101003351/161268433-f4c321b7-1e6e-4d3d-9086-b628170e032b.PNG)

**Comment by LeonLeprau** [comment]
Hi Dhersz,

Its odd I can put in like the first 250 stop_id's and it works, but then as soon as I add the next one i'm presented with +. looking at the specific stop_id that appears to be causing the problem it is literally the exact same as the rest.

e.g. pic 1 the first batch comes back perfectly 

![Capture 3](https://user-images.githubusercontent.com/101003351/161302745-5429c257-5466-4a7b-87ab-86d96a17f80b.PNG)

Then as soon as I add the stop_id ending in 4069 its no go. I've even tried taking that one out and the following few lines but still comes back with a (+). It's almost like it wont go past certain point in the data.


![Capture 4](https://user-images.githubusercontent.com/101003351/161302781-0008c2c6-0fdb-4e58-b889-c95605fa17f9.PNG)
 
Thanks so much for helping me with this, your a legend :)
all the best

**Comment by dhersz** [comment]
I'm not sure I can help you here, the issue seems not to be related to gtfstools in any way.

What I'd recommend you is to stop copying-and-pasting all of these stop_ids manually, and retrieve them in a programmatic way, somehow. You could use a regular expression, for example, to select the few stop_ids you want to keep, or maybe generate them combining `format()` and `paste()`.

I think that would improve your efficiency and make your work less error-prone. For now I'll be closing this issue, since it's not related to the package.
